/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2023-09-06 17:14:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.JSONObject;
import org.json.JSONException;
import java.util.Map;
import com.util.Logging;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.util.*;
import com.scb.ivr.spring.appcontext.SpringApplicationContext;
import com.scb.ivr.model.uaas.ValidateOTP_Req;
import com.scb.ivr.model.uaas.ValidateOTP_Res;
import com.scb.ivr.controller.UAASController;
import java.text.SimpleDateFormat;
import com.scb.util.GlobalConstant;
import org.json.JSONObject;
import com.genesyslab.studio.backendlogic.GVPHttpRequestProcessor;
import java.util.Map;

public final class OtpValidation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


// Implement this method to execute some server-side logic.
public JSONObject performLogic(JSONObject state, Map<String, String> additionalParams) throws Exception {
    
	JSONObject result = new JSONObject();
    String sessionID = state.getString("GVPSessionID").split(";")[0];
    String callID = state.getString("CallUUID").trim();
   JSONObject appSession = state.getJSONObject("appSession");    
   String loggerName = appSession.getString("loggerName");
   Date timeStamp = new Date();
   Logger debugLogger = null;
	String className = new Object(){}.getClass().getEnclosingClass().getName();
	className = className.split("[.]")[4];
	String loggingCommonFormat =  "{" + sessionID + "}," + callID + "," + className + ","; 
	debugLogger=Logging.LoggerConfiguration(sessionID);
	String ucid = 	appSession.getString("ucid");

    try{
		  debugLogger.debug(loggingCommonFormat + "***************Otp Validation Block Entry**************************");
		  	 debugLogger.debug(loggingCommonFormat + "AppSession Starting value : "+ appSession);

		  	 UAASController controller = (UAASController) SpringApplicationContext.getBean("UAASController");
    	 String profileid= appSession.getString("relID");
    	 String otpinput= state.getString("otpNum");
    	 String modulus="b6b44e815345da9297e595cc88bd6ba7ac5fe4d08bb7aa795951b71b093ad0e0bde4b638570ca038ba0d73222c62286c6a926793f88ae411280c3b92ac5c79d2c142d4a600a376420e101a31936697c2adb56ee0e96be21320eacfefe7f97fd5ad0e59bbf1ff75efa2ae50b6fdb3acd46e89fd993efe4fbf775a071c19d9d694c6f97a47fdd64df0b87338aa839db9b4d5cc907de7c409c5fd7db5921123081b766f795afcb70a7fce5b953a9c4b557b5cebed277cec522fe752c09706d571ebb6620ebdece8c6cd66fc146f562dc5b674cba1361afc6bbe2f050558071b691a0e67e6e57bc9abb8ee64971c23ef14302ab27643fcfad50e123af630c9bc77d9";
    	 String encryptblock="MTY2MTM0OTI5MTgyMl8tX1ZOVl8tX0hLXy1fMzYwMzMyODQyXy1fcGI0ZWliWG5fLV9uZkt4amZ3MENtSWZaemxzeDdvV2JwbEV1OG9VVU15b2hjdkJQZys5aGxZPQ==";
    	 ValidateOTP_Req reqObj = new ValidateOTP_Req();
    	 reqObj.setRelID(profileid);
    	 reqObj.setUcid(ucid);
    	 reqObj.setHotline(appSession.getString("DNIS"));
    	 reqObj.setModulus(modulus);
    	 reqObj.setEncryptedBlock(encryptblock);	
    	 reqObj.setExponent("10001");
    	 reqObj.setKeyIndex("3");
    	 reqObj.setOtp(otpinput);
    	 reqObj.setOtpSn("311731");
    	 reqObj.setSessionId(sessionID);
    	 debugLogger.debug(loggingCommonFormat + "This All request to validateOTP method requests  : "+ reqObj);
    	 debugLogger.debug(loggingCommonFormat + "OTP Input from Customer is  : "+ otpinput);
    	 ValidateOTP_Res res = controller.validateOTP(reqObj);
    	 debugLogger.debug(loggingCommonFormat + "USER ENTERED OTP INPUT is VALID  AND THE STATUSCODE IS:" +res.getResponse().getStatusCode());
		  debugLogger.debug(loggingCommonFormat + "ErrorCode :"+  res.getErrorcode());
		  debugLogger.debug(loggingCommonFormat + "ErrorMessage :"+   res.getErrormessage());
		  debugLogger.debug(loggingCommonFormat + "StartTime :"+     res.getStartTime());
		  debugLogger.debug(loggingCommonFormat + "EndTime :"+       res.getEndTime());
		  debugLogger.debug(loggingCommonFormat + "OTP VALID response  "+  res.getResponse());
    	 if(GlobalConstant.HOST_SUCCESS_CODE.equalsIgnoreCase(res.getErrorcode())){
    		 if("100".equalsIgnoreCase(res.getResponse().getStatusCode())){
    	    		debugLogger.debug(loggingCommonFormat + "OTP VALIDATION SUCCESSFULL");
			  appSession.put("validotp","Valid");
			  appSession.put("OTPAUTH","S");
			  appSession.put("VERIFIEDBY","OTP");
			  appSession.put("OTP_DEST",appSession.getString("MOBILE"));
    		 }
		else if("308".equalsIgnoreCase(res.getResponse().getStatusCode())){
    		debugLogger.debug(loggingCommonFormat + "INVALID OTP VALIDATION");
			  appSession.put("validotp","Invalid");
			  appSession.put("OTPAUTH","F");
			  
		  }else if("368".equalsIgnoreCase(res.getResponse().getStatusCode())){
	    		debugLogger.debug(loggingCommonFormat + "OTP HAS BEEN BLOCKED");
			  appSession.put("validotp","Blocked");
				appSession.put("OTPAUTH","F");
			 
		  }else if("307".equalsIgnoreCase(res.getResponse().getStatusCode())){
	    		debugLogger.debug(loggingCommonFormat + "OTP HAS BEEN EXPIRED");
			  appSession.put("validotp","Expired");
				appSession.put("OTPAUTH","F");
			 
		  }else if("330".equalsIgnoreCase(res.getResponse().getStatusCode())){
	    		debugLogger.debug(loggingCommonFormat + "INVALID OTP TOKEN");
			  appSession.put("validotp","invalidOtpToken");
				appSession.put("OTPAUTH","F");

		  }
		  else{
	    		debugLogger.debug(loggingCommonFormat + "ERROR WHILE VALIDATE OTP");
			  appSession.put("validotp","Error");
				appSession.put("OTPAUTH","F");
		  }
    	 }
    	 else if("111111".equalsIgnoreCase(res.getResponse().getStatusCode())){
      		debugLogger.debug(loggingCommonFormat + "Failure Exception or Validation Error Message/Unknown Error");
  			  appSession.put("validotp","error");
  				appSession.put("OTPAUTH","F");
  			  
  		  }
    	 else if("001308".equalsIgnoreCase(res.getResponse().getStatusCode())){
     		debugLogger.debug(loggingCommonFormat + "INVALID OTP VALIDATION");
 			  appSession.put("validotp","Invalid");
 				appSession.put("OTPAUTH","F");
 			  
 		  }else if("001368".equalsIgnoreCase(res.getResponse().getStatusCode())){
 	    		debugLogger.debug(loggingCommonFormat + "OTP HAS BEEN BLOCKED");
 			  appSession.put("validotp","Blocked");
 				appSession.put("OTPAUTH","F");
 			 
 		  }else if("001307".equalsIgnoreCase(res.getResponse().getStatusCode())){
 	    		debugLogger.debug(loggingCommonFormat + "OTP HAS BEEN EXPIRED");
 			  appSession.put("validotp","Expired");
 				appSession.put("OTPAUTH","F");
 			 
 		  }else if("001330".equalsIgnoreCase(res.getResponse().getStatusCode())){
 	    		debugLogger.debug(loggingCommonFormat + "INVALID OTP TOKEN");
 			  appSession.put("validotp","invalidOtpToken");
 				appSession.put("OTPAUTH","F");

 		  }
		  else{
	    		debugLogger.debug(loggingCommonFormat + "ERROR WHILE VALIDATE OTP");
			  appSession.put("validotp","Error");
				appSession.put("OTPAUTH","F");

		  }
		  debugLogger.debug(loggingCommonFormat + "validotp  status : "+  appSession.getString("validotp"));
		  	 debugLogger.debug(loggingCommonFormat + "AppSession End Value : "+ appSession);
		  debugLogger.debug(loggingCommonFormat + "***************Otp Validation Block Exit**************************");
    }catch(Exception e){
    	 debugLogger.error(loggingCommonFormat + "Exception :" +e);
		  appSession.put("validotp","Error");
			appSession.put("OTPAUTH","F");
    }
    String ONEFA=appSession.getString(GlobalConstant.ONEFA);
    String[] split = ONEFA.split(",");
	String oneFAChange="";
	for (String value : split) {
		String[] split2 = value.split("[|]");
		if(split2[0].equalsIgnoreCase("OTP")) {
			oneFAChange=oneFAChange+"OTP"+"|"+appSession.getString("OTPAUTH");
		}
		else{
			oneFAChange=oneFAChange.concat(value)+",";
		}
	}
	appSession.put(GlobalConstant.ONEFA,oneFAChange);
	debugLogger.debug("oneFA value : " + appSession.getString(GlobalConstant.ONEFA));
	  result.put("appSession",appSession);
    return result;
    
};


/* public JSONObject performLogic(JSONObject state, Map<String, String> additionalParams)
{
    return new JSONObject();
} */

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/src/../include/backend.jspf", Long.valueOf(1691499940833L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.scb.ivr.model.uaas.ValidateOTP_Req");
    _jspx_imports_classes.add("com.scb.ivr.spring.appcontext.SpringApplicationContext");
    _jspx_imports_classes.add("com.scb.ivr.model.uaas.ValidateOTP_Res");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.util.Logging");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("org.apache.logging.log4j.Logger");
    _jspx_imports_classes.add("com.scb.util.GlobalConstant");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.scb.ivr.controller.UAASController");
    _jspx_imports_classes.add("com.genesyslab.studio.backendlogic.GVPHttpRequestProcessor");
    _jspx_imports_classes.add("org.apache.logging.log4j.LogManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write(" \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
      out.write("\r\n\r\n\r\n\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

response.setHeader("Cache-Control", "no-cache");
/* response.addHeader("X-Frame-Options", "DENY"); */     // Setting the "DENY" Flag on response object to restrict browsers that support this header from allowing embedding web-pages in a frame

 /* Logger logger = BackendLogManager.getLogger("backEnd"); */
String output = null; 

try {
    // process the post data
    GVPHttpRequestProcessor processor = new GVPHttpRequestProcessor(request);
    processor.parseRequest();
    
    // "state" encapsulates the state variable submitted by the VXML page
    JSONObject state = processor.getState();
    
    // additional parameters that were passed in the namelist
    Map<String, String> additionalParams = processor.getAdditionalParams();
    
    // perform the logic
    JSONObject result = performLogic(state, additionalParams);
    
    output = result.toString();
    
    out.print(output);
    /* logger.info("Output: " + output); */
    
} catch (Exception e) {
    
    //Removed the call to 'e.printstacktrace()' as printing the stack trace of an exception is a bad practice.
    
    //String msg = e.getMessage();
    //if (null != msg){
    //    msg = msg.replace('"', '\'');
    //}
    
     e.printStackTrace();
        String msg = e.getMessage();
        if (null != msg){
            msg = msg.replace('"', '\'');
        }
    out.print("An error has occured in the custom backend JSP file");
    /* logger.error("An error has occured in the custom backend JSP file"); */
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
